export default {
  pointer: "normal",
  help: "help select",
  work: "working in background",
  busy: "busy",
  cross: "precision select",
  text: "text select",
  hand: "handwriting",
  unavailiable: "unavailable",
  vert: "vertical resize",
  horz: "horizontal resize",
  dgn1: "diagonal resize 1 \\",
  dgn2: "diagonal resize 2 /",
  move: "move",
  alternate: "alternate select",
  link: "link select",
  location: "location select",
  person: "person select",
} as const;